In [1]:
import pandas as pd

def concat_last_rows(csv_files, name_index):
    last_rows = []
    for file in csv_files:
        df = pd.read_csv(file)
        last_rows.append(df.tail(1))
    result = pd.concat(last_rows, ignore_index=True)
    result.drop('Image_ID', axis=1, inplace=True)
    result.index = name_index
    return result

def simplify_print_data(df):
    psnr_diff = df['PSNR_Output'] - df['PSNR_Input']
    mse_diff =  df['MSE_Output'] - df['MSE_Input']
    mae_diff = df['MAE_Output'] - df['MAE_Input']
    maxae_diff = df['MaxAE_Output'] - df['MaxAE_Input']
    result = pd.DataFrame({
        'PSNR_Diff':psnr_diff,
        'MSE_Diff':mse_diff,
        'MAE_Diff':mae_diff,
        'MaxAE_Diff':maxae_diff
    }, index=df.index)
    return result

experiments_dir = "/projects/memaro/rpujol/unfolding/experiments/"
name_file = 'metrics.csv'

In [9]:
date = "2026-02-0"
expe_dir_act = experiments_dir + date
csv_list = [expe_dir_act+"5_15-49/"+name_file,expe_dir_act+"5_16-57/"+name_file,expe_dir_act+"6_11-43/"+name_file]
name_index = ["0.0001","0.01","0"]
df_last = concat_last_rows(csv_list, name_index)
display(df_last)
df_simplify = simplify_print_data(df_last)
display(df_simplify)
stats = df_simplify.agg(['mean', 'std'])
display(stats)

,PSNR_Input,PSNR_Output,MSE_Input,MSE_Output,MAE_Input,MAE_Output,MaxAE_Input,MaxAE_Output
0.0001,1.376,13.802,0.732,0.048,0.778,0.187,1.0,0.874
0.01,1.376,13.863,0.732,0.046,0.778,0.180,1.0,0.883
0,1.376,13.869,0.732,0.047,0.778,0.184,1.0,0.858

        PSNR_Diff  MSE_Diff  MAE_Diff  MaxAE_Diff
0.0001     12.426    -0.684    -0.591      -0.126
0.01       12.487    -0.686    -0.598      -0.117
0          12.493    -0.685    -0.594      -0.142

      PSNR_Diff  MSE_Diff  MAE_Diff  MaxAE_Diff
mean  12.468667    -0.685 -0.594333   -0.128333
std    0.037072     0.001  0.003512    0.012662

In [3]:
date = "2025-11-1"
expe_dir_act = experiments_dir + date
csv_list = [expe_dir_act+"8_15-00/"+name_file,expe_dir_act+"9_15-17/"+name_file,expe_dir_act+"9_16-35/"+name_file,expe_dir_act+"9_17-56/"+name_file,expe_dir_act+"9_20-21/"+name_file]
name_index = ["Taylor-2","Cayley-2","Cayley-3","Cayley-4","Cayley-5"]
df_last = concat_last_rows(csv_list, name_index)
display(df_last)
df_simplify = simplify_print_data(df_last)
display(df_simplify)

,PSNR_Input,PSNR_Output,MSE_Input,MSE_Output,MAE_Input,MAE_Output,MaxAE_Input,MaxAE_Output
Taylor-2,1.121,10.927,0.776,0.090,0.806,0.223,1.0,0.973
Cayley-2,1.121,10.635,0.776,0.091,0.806,0.252,1.0,0.985
Cayley-3,1.121,10.875,0.776,0.092,0.806,0.230,1.0,0.948
Cayley-4,1.121,7.944,0.776,0.177,0.806,0.288,1.0,1.000
Cayley-5,1.121,7.763,0.776,0.173,0.806,0.276,1.0,1.000

          PSNR_Diff  MSE_Diff  MAE_Diff  MaxAE_Diff
Taylor-2      9.806    -0.686    -0.583      -0.027
Cayley-2      9.514    -0.685    -0.554      -0.015
Cayley-3      9.754    -0.684    -0.576      -0.052
Cayley-4      6.823    -0.599    -0.518       0.000
Cayley-5      6.642    -0.603    -0.530       0.000